trigger:
  branches:
    include:
    - master
  paths:
    include:
    - ServerApp/*
    - ServerApp.IntegrationTests/*
    - azure-pipelines.yml
    - SportsStoreApp.sln

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Debug'

steps:
- task: UseDotNet@2
  displayName: 'Setup .NET Core'
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '**/*.sln'
    feedsToUse: 'select'
    verbosityRestore: 'Minimal' 

- task: CmdLine@2
  displayName: 'Libman'
  inputs:
    script: |
      dotnet tool restore
      dotnet libman restore
    workingDirectory: 'src\SportsStore'

- task: SonarCloudPrepare@1
  displayName: Prepare SonarCloud analysis
  inputs:
    SonarCloud: 'feliperomero3-sonarcloud'
    organization: 'feliperomero3'
    scannerMode: 'MSBuild'
    projectKey: 'feliperomero3_SportsStoreApp_ServerApp'
    projectName: 'SportsStoreApp_ServerApp'
    projectVersion: '1.0'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: build
    projects: '**/*.sln'
    arguments: '--no-restore --configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: '**/*Test*/*.csproj'
    arguments: '--no-build --configuration $(buildConfiguration) --collect "Code Coverage"'

- task: SonarCloudAnalyze@1
  displayName: 'Run SonarCloud analysis'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/!(*Test*).csproj'
    arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: '$(Build.DefinitionName)_$(Build.BuildNumber)'

- task: SonarCloudPublish@1
  displayName: 'Publish SonarCloud analysis results'
  inputs:
    pollingTimeoutSec: '300'
