name: SportsStoreClientApp-CI

on:
  push:
    branches: [ master ]
    paths: ClientApp
  pull_request:
    branches: [ master ]
    paths: ClientApp

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      env:
        NODE_VERSION: '13.x'
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Clean install
      working-directory: ClientApp
      run: npm ci
    - name: Build
      working-directory: ClientApp
      run: npm run build
    - name: Lint
      working-directory: ClientApp
      run: npm run lint
