name: SportsStoreServerApp-CI

on:
  push:
    branches: [ master ]
    paths: 'ServerApp/**'
  pull_request:
    branches: [ master ]
    paths: 'ServerApp/**'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository 
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
      run: dotnet restore --verbosity normal
    - name: Build
      run: dotnet build --configuration Debug --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
