name: SportsStoreClientApp-CI

on:
  push:
    branches: [ master ]
    paths:
    - 'ClientApp/**'
    - '**/SportsStoreClientApp-CI.yml'
  pull_request_target:
    branches: [ master ]
    paths:
    - 'ClientApp/**'
    - '**/SportsStoreClientApp-CI.yml'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node.js ${{ env.NODE_VERSION }}
      env:
        NODE_VERSION: '12.x'
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Clean install
      working-directory: ClientApp
      run: npm ci
    - name: Lint
      working-directory: ClientApp
      run: npm run lint
    - name: Build
      working-directory: ClientApp
      run: npm run build
    - name: Test
      working-directory: ClientApp
      run: npm run test
  sonarcloud:
    name: sonarcloud
    runs-on: ubuntu-latest
    environment: default
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Node.js ${{ env.NODE_VERSION }}
      env:
        NODE_VERSION: '12.x'
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Clean install
      working-directory: ClientApp
      run: npm ci
    - name: Test
      working-directory: ClientApp
      run: npm run test
    - name: Replace SF directories in coverage/lcov.info
      working-directory: ClientApp
      run: sed -i 's+/home/runner/work/SportsStoreApp/SportsStoreApp+/github/workspace+g' coverage/SportsStore/lcov.info
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v3.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: ClientApp
