name: SportsStoreServerApp-CI

on:
  push:
    branches: [ master ]
    paths:
    - 'ServerApp/**'
    - '**/SportsStoreServerApp-CI.yml'
  pull_request:
    branches: [ master ]
    paths:
    - 'ServerApp/**'
    - '**/SportsStoreServerApp-CI.yml'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository 
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: 3.1.x
    - name: Restore
      run: dotnet restore --verbosity minimal
    - name: Build
      run: dotnet build --no-restore --configuration Debug
    - name: Test
      run: dotnet test --no-build --logger trx --collect "Code Coverage" --configuration Debug --verbosity normal
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: ServerApp
